"""empty message

Revision ID: 077358a2baa8
Revises: ffdc0a98111c
Create Date: 2022-01-07 10:45:55.698629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '077358a2baa8'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('components', 'complete',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_foreign_key(None, 'components', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'components', 'users', ['user_id'], ['id'])
    op.alter_column('projects', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('projects', 'complete',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_foreign_key(None, 'projects', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'resources', 'categories', ['cat_id'], ['id'])
    op.create_foreign_key(None, 'resources', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'tables', 'datatypes', ['datatype_id'], ['id'])
    op.create_foreign_key(None, 'tables', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'technologies', 'categories', ['cat_id'], ['id'])
    op.create_foreign_key(None, 'technologies', 'resources', ['resource_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'technologies', type_='foreignkey')
    op.drop_constraint(None, 'technologies', type_='foreignkey')
    op.drop_constraint(None, 'tables', type_='foreignkey')
    op.drop_constraint(None, 'tables', type_='foreignkey')
    op.drop_constraint(None, 'resources', type_='foreignkey')
    op.drop_constraint(None, 'resources', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.alter_column('projects', 'complete',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('projects', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'components', type_='foreignkey')
    op.drop_constraint(None, 'components', type_='foreignkey')
    op.alter_column('components', 'complete',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
