"""create_users_table

Revision ID: ffdc0a98111c
Revises:
Create Date: 2020-11-20 15:06:02.230689

"""
from sqlalchemy.sql.schema import Column
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffdc0a98111c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_handle', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('linkdin', sa.String(length=50), nullable=False),
    sa.Column('bio', sa.Text, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('github_handle')
    )
    op.create_table('datatypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('datatype_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('datatype_spec', sa.Integer, nullable=True),
    sa.Column('null', sa.Boolean, nullable=False),
    sa.Column('relationship', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cat', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resources_array', sa.Text, nullable=True),
    sa.Column('tech_array', sa.Text, nullable=True),
    sa.Column('wireframing_array', sa.Text, nullable=True),
    sa.Column('description', sa.Text, nullable=False),
    sa.Column('github_link', sa.String(length=100), nullable=True),
    sa.Column('complete', sa.Boolean, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text, nullable=False),
    sa.Column('complete', sa.Boolean, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cat_id', sa.Integer(), nullable=False),
    sa.Column('ref_link', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###qqqqqqqqq


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('datatypes')
    op.drop_table('tables')
    op.drop_table('categories')
    op.drop_table('projects')
    op.drop_table('components')
    op.drop_table('resources')
    # ### end Alembic commands ###
